apiVersion: apps/v1
kind: Deployment
metadata:
  name: fox-api
  namespace: fox
  labels:
    app: fox-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fox-api
  template:
    metadata:
      labels:
        app: fox-api
    spec:
      containers:
      - name: api
        image: ghcr.io/hokita/fox-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: fox-config
              key: db-name
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/articles
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/articles
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: fox
  labels:
    app: fox-api
spec:
  type: ClusterIP
  selector:
    app: fox-api
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
