apiVersion: apps/v1
kind: Deployment
metadata:
  name: fox-api
  namespace: fox
  labels:
    app: fox-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fox-api
  template:
    metadata:
      labels:
        app: fox-api
    spec:
      containers:
      - name: api
        image: ghcr.io/hokita/fox-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: fox-api-secrets
              key: db-endpoint
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: fox-api-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fox-api-secrets
              key: db-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: fox-api-secrets
              key: db-name
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: fox
  labels:
    app: fox-api
spec:
  type: NodePort
  selector:
    app: fox-api
  ports:
  - name: http
    port: 3001
    targetPort: 3001
    nodePort: 30007
    protocol: TCP
