apiVersion: apps/v1
kind: Deployment
metadata:
  name: fox-fe
  namespace: fox
  labels:
    app: fox-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fox-fe
  template:
    metadata:
      labels:
        app: fox-fe
    spec:
      containers:
        - name: frontend
          image: ghcr.io/hokita/fox-fe:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NODE_ENV
              value: "production"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: fe-service
  namespace: fox
  labels:
    app: fox-fe
spec:
  type: NodePort
  selector:
    app: fox-fe
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30008
      protocol: TCP
