name: API CI

on:
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - '.github/workflows/api-ci.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'api/**'
      - '.github/workflows/api-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './api/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

      - name: Run tests
        run: npm test

      - name: Build TypeScript
        run: npm run build
